trigger:
- main

name: $(Date:yyyy.MM.dd).$(Rev:r)

pool:
  vmImage: ubuntu-latest

variables:
  azureSubscription: 'sw-development-connection'
  dockerRegistryServiceConnection: 'cmgdev-acr'
  appName: 'webauthn-test-api'
  containerRegistryNamespace: 'cmgdev.azurecr.io'
  imageRepository: 'webauthn-test/api'
  tag: $(Build.BuildNumber)

stages:
- stage: Deploy_API
  displayName: Build and Deploy API
  jobs:
  - job: Deploy_API
    displayName: Build and Deploy API
    steps:  
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: |
          $(tag)
          latest
    - task: AzureRmWebAppDeployment@4
      displayName: Deploy to App Service
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: $(azureSubscription)
        appType: 'webAppContainer'
        WebAppName: $(appName)
        DockerNamespace: $(containerRegistryNamespace)
        DockerRepository: $(imageRepository)
        DockerImageTag: $(tag)