trigger:
- main

name: $(Date:yyyy.MM.dd).$(Rev:r)

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'webauthn-test/api'
  dockerRegistryServiceConnection: ''

stages:
- stage: Build API
  jobs:
  - job: Build API
    displayName: Build API
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: buildAndPush
        dockerfile: ./server/Dockerfile
        containerRegistry: dockerRegistryServiceConnection
        repository: $(imageName)
        tags: |
          $(buildNumber)
          latest
    #TODO: Restart app service