version: '3.1'

services:

  web: 
    build:
      context: ./client
      target: run
      args:
        - PORT=3000
        - NODE_ENV=development
        - API_URL=http://localhost:10001
    ports:
      - 10000:3000

  api:
    build:
      context: ./server
    command: ["/wait-for-it.sh", "database:1433", "-t", "30", "--", "dotnet", "WebAuthnTest.Api.dll"]
    ports:
      # in development, the Nuxt dev server proxies "/api" routes to the asp.net core app on this port
      - 10001:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SQLCONNSTR_DEFAULT: Server=database;Database=WebAuthnTest;MultipleActiveResultSets=True;User Id=sa;Password=AdminPassword9@;
      APP_URL: https://localhost:10000
    volumes:
      - .\wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - database

  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    #mapping to a port on the host isnt necessary, but it's helpful if you want to connect
    #to the database using SQL Server Management Studio
    ports:   
      - 1433:1433
    environment:
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: "AdminPassword9@"
      ACCEPT_EULA: "Y"
    volumes:
      - database:/var/opt/mssql

volumes:
  database: