version: '3.1'

services:

  api:
    build:
      context: .
    command: /start-api.sh
    ports:
      - 10001:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SQLCONNSTR_DEFAULT: Server=database;Database=WebAuthnTest;MultipleActiveResultSets=True;User Id=sa;Password=AdminPassword9@;
      WEB_URL: https://localhost:10000
      Logging__LogLevel__Default: Debug
    volumes:
      - ./start-api.sh:/start-api.sh
    depends_on:
      - database

  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    # mapping to a port on the host isnt necessary, but it's helpful if you want to connect
    # to the database using SQL Server Management Studio
    ports:
      - 1433:1433
    environment:
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: "AdminPassword9@"
      ACCEPT_EULA: "Y"
    volumes:
      - database:/var/opt/mssql

volumes:
  database:
